package com.jihun.searchweather

enum class ViewType {
    EMPTY,
    DIVIDER,

    MAIN_ITEM_HEADER,
    MAIN_ITEM,

    DETAIL_CURRENT_WEATHER,

    DETAIL_HOURLY_WEATHER,
    DETAIL_HOURLY_CONTENT,
    DETAIL_HOURLY_DATE_DIVIDER,

    DETAIL_DAILY_WEATHER
}