package com.jihun.searchweather

enum class ViewType {
    EMPTY,
    MAIN_ITEM_HEADER,
    MAIN_ITEM,
    MAIN_AUTO_COMPLETE_ITEM,
    DETAIL_CURRENT_WEATHER,
    DETAIL_HOURLY_WEATHER_TAB,
    DETAIL_HOURLY_WEATHER_CONTENT,
    DETAIL_DAILY_WEATHER
}